/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ihoneymon' at '14. 4. 15 오전 11:45' with Gradle 1.11
 *
 * @author ihoneymon, @date 14. 4. 15 오전 11:45
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
